---
title: "IRC_Data_Analysis_Training_2"
author: "Rachel Kenny"
date: "1/11/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load packages
```{r load_packages}

# Load packages
library(tidyverse) 
library(here) 
library(janitor)
library(readxl)

```

### Load data
```{r load_data}

# Load oak data
oak_data_raw <- read_csv(here("data", "Weir_Oak_Restoration_Data_winter19.csv"))
oak_data <- clean_names(oak_data_raw)

# Load agua chinon veg data
ac_data_raw <- read_excel(here("data", "OCWR_AC_2019_Data.xlsx"))
ac_data <- clean_names(ac_data_raw)

```

## Subsetting data
```{r subset}

# To refer to specific column in a dataframe, use the [$] symbol
oak_data$height_cm
View(oak_data$height_cm)


View(oak_data)

# You can also refer to the number of the column using square brackets []. Using a colon indicates subsequent columns. For example [4:6] means columns 4 through 6. Using a negative means everything except for that column.
oak_data[4] # column 4
oak_data[4:6] # column 4-6
oak_data[-4] # everything except for column 4


# A comma before the number indicates a column (though it is not necessary), while a comma after the number indicates a row and IS necessary.

# FOR EXAMPLE:

# To return column 3
ac_data[3]
# OR
ac_data[,3]

# To return row 3
ac_data[3,]

# To return columns 1-3
ac_data[1:3]
# OR
ac_data[,1:3]

# To return rows 1-3
ac_data[1:3,]


# Single brackets extract a list
ac_data[5]

# Double brackets extract the items in a list
ac_data[[5]]


ac_data[5,3]

```

### Data wrangling (part 1)
```{r wrangle1}

# Use the which() function to refer to specific observations in the code. In this example, we are replacing the words "5M Buffer" in the polygon ID column with the words "5M BUFFER" so that R will recognize these polygon IDs as being the same
ac_data$polygon_id[which(ac_data$polygon_id=="5M Buffer")] <- "5M BUFFER"

# There are a few ways to rename a column
# Method 1: use function [colnames] 
df <- ac_data
colnames(df)[4:6] <- c("pin", "type_data", "code_species") # rename columns 4 through 6

# Method 2: use function [names] 
df <- ac_data
names(df)[1] <- paste("habitat") # name column 1 "habitat"

View(df)

```


### Data wrangling (part 2)
```{r wrangle2}

# There are a few ways to create a new column
# Method 1: Use the function [mutate]. Within the new column you can make transformations on your data.
oak_data2 <- oak_data %>% 
  mutate(new_column=height_cm*2)

# Method 2: Create a new column using the [$] symbol
oak_data3 <- oak_data
oak_data3$height_rounded <- round(oak_data3$height_cm)

View(oak_data2)
View(oak_data3)

```


### Creating tables
```{r tables}

# To count observations by group, use the [group_by] and [count] functions. Here are two examples below

# agua chinon data example - number of observations per species code in each polygon and transect
richness1 <- ac_data %>%
  group_by(polygon_id, transect) %>% 
  count(species_code)

View(richness1)

# richness2 - add column for the number of unique species per transect
richness2 <- richness1 %>% 
  mutate(unique_species=n_distinct(species_code)) %>% 
  select(transect, polygon_id, unique_species)
richness2 <- distinct(richness2)
View(richness2)

# oak data example - # of plantings watered or not watered by sampling group
oak_water_sampling_grp <- oak_data %>% 
  group_by(sampling_group) %>% 
  count(survival)

View(oak_water_sampling_grp)
View(oak_data)

```

